<a href="https://colab.research.google.com/github/manuela1702/elephant_migration/blob/main/elephant_migration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# imports
import pandas as pd
import numpy as np
from google.colab import drive

# connecting to Google Drive
drive.mount('/content/drive')

# loading dataset
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/African elephants.csv')

# overview of the first lines
print(df.shape)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(99988, 10)

,event-id,visible,timestamp,location-long,location-lat,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individual-local-identifier,study-name
0,7980499272,True,2008-10-30 00:15:00.000,16.202088,-19.063725,gps,Loxodonta africana,AG005,LA5,African elephants in Etosha National Park (dat...
1,7980499273,True,2008-10-30 02:46:00.000,16.209496,-19.069908,gps,Loxodonta africana,AG005,LA5,African elephants in Etosha National Park (dat...
2,7980499274,True,2008-10-30 03:31:00.000,16.214184,-19.068719,gps,Loxodonta africana,AG005,LA5,African elephants in Etosha National Park (dat...
3,7980499275,True,2008-10-30 03:45:00.000,16.214170,-19.068683,gps,Loxodonta africana,AG005,LA5,African elephants in Etosha National Park (dat...
4,7980499276,True,2008-10-30 05:31:00.000,16.229372,-19.058258,gps,Loxodonta africana,AG005,LA5,African elephants in Etosha National Park (dat...

In [11]:
# Select only needed columns
df = df[['timestamp', 'location-lat', 'location-long', 'individual-local-identifier']]

# Rename columns for easier use
df.columns = ['timestamp', 'lat', 'lon', 'elephant_id']

# Convert timestamp string to datetime format
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Remove rows with missing values
df = df.dropna()

# Verify result
print(df.shape)
df.head()

(99988, 4)

            timestamp        lat        lon elephant_id
0 2008-10-30 00:15:00 -19.063725  16.202088         LA5
1 2008-10-30 02:46:00 -19.069908  16.209496         LA5
2 2008-10-30 03:31:00 -19.068719  16.214184         LA5
3 2008-10-30 03:45:00 -19.068683  16.214170         LA5
4 2008-10-30 05:31:00 -19.058258  16.229372         LA5